### ISSUE TITLE
Can we detect the fundamental of some notes from a musical instrument with fft-real?

### ISSUE THREAD

**Issue by aalex** [cyrilcode/fft-real#1]
Hi,
I am looking at the Qt "Spectrum example" sample project that uses FFTReal. (I am not sure which version) What I would like to do is to guess the fundamental of some music notes, played by an instrument. I want to build a tuner. Would that be possible with FFTReal? Should I use FFTReal for such a task, or would FFTW be faster? How can I achieve this?
Thank you!

**Comment by darrenmothersele** [comment]
Hi aalex, I'm just hosting this copy of fftreal here as it made the build process of one of my projects easier. It's not my library, and I can't support it.

But, it might be what you're looking for. Here's a couple of useful/interesting links I found:

https://www.codeproject.com/Articles/32172/FFT-Guitar-Tuner

https://arxiv.org/pdf/0912.0745.pdf

I hope that helps.
